Client:
    type: entity
    table: client
    id:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_client
            generator:
                strategy: SEQUENCE
    fields:
        firstname:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        lastname:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        civility:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        zip:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
        country:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        login:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
